### ISSUE TITLE
Account field is not following EIP-1052

### ISSUE THREAD

**Issue by jonathanpwang** [axiom-crypto/axiom-tools#9]
https://github.com/axiom-crypto/axiom-tools/blob/43891b2d93228cb12d48b5612c4256f4d2ed9af7/src/rpc/subqueryField.ts#L520

codeHash is not returning correctly for EOA accounts: https://eips.ethereum.org/EIPS/eip-1052

**Comment by ytham** [comment]
https://github.com/axiom-crypto/axiom-tools/pull/10

**Comment by ytham** [comment]
@jonathanpwang it seems that `codeHash` is returning correctly for EOAs in the current implementation? bytes32(0) if account has not been created yet, and keccak256() if it is. 

However, `storageHash` is currently `0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421` for EOAs that are not yet created and the same value after they are created, but querying the provider directly returns bytes32(0) for `storageHash` if the EOA has not been created yet and `0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421` if it has been created.

**Comment by jonathanpwang** [comment]
I believe `storageHash` should always be `0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421` for accounts that are not created, and also for EOAs.

`codeHash` looks correct, then, my mistake.

**Comment by ytham** [comment]
alright, seems like that's the current behavior. closing this issue.
